/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entidades.*;
import Procesos.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roban
 */
public class BusquedaAvanzada extends javax.swing.JFrame {

    /**
     * Creates new form BusquedaAvanzada
     */
    static Usuario usuario;
    private static Factory factory;
    
    public BusquedaAvanzada(Usuario usuario) {
        factory = new Factory();
        initComponents();
        this.usuario = usuario;
        cargarColumnasTabla();
        BaseDatos base = factory.basedatos();
        cargarModeloTabla(base.obtenerMovimientosTODOS());
        
        this.Date_desde.setVisible(false);
        this.Date_hasta.setVisible(false);
        this.lbl_desde.setVisible(false);
        this.lbl_hasta.setVisible(false);
        
        this.setLocationRelativeTo(null);
    }

    DefaultTableModel modeloTabla = new DefaultTableModel();

    private void cargarColumnasTabla(){
        
        modeloTabla.addColumn("Descripcion");
        modeloTabla.addColumn("Tipo de Movimiento");
        modeloTabla.addColumn("Fecha");
        modeloTabla.addColumn("Monto");
  
    }
    
    private void cargarModeloTabla(ArrayList<Movimiento> listado){
        
        ArrayList<Movimiento> listaMovimientos = listado;
        int numeroMovimientos = listaMovimientos.size();
        modeloTabla.setNumRows(numeroMovimientos);
        
        for(int i =0;i<numeroMovimientos;i++){
            Movimiento movimientos = listaMovimientos.get(i);
            
            String descripcion = movimientos.getDescripcion();
            String tipoMov = movimientos.getTipomovimiento();
            String fecha = movimientos.getFecha();
            Double monto = movimientos.getMonto();

            
            
            modeloTabla.setValueAt(descripcion, i, 0);
            modeloTabla.setValueAt(tipoMov, i, 1);
            modeloTabla.setValueAt(fecha, i, 2);
            modeloTabla.setValueAt("$ "+monto, i, 3);
      
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup_selector = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_movimientos = new javax.swing.JTable();
        lbl_overTeibul = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        rbtn_descripcion = new javax.swing.JRadioButton();
        rbtn_tipoMov = new javax.swing.JRadioButton();
        rbtn_fecha = new javax.swing.JRadioButton();
        txt_busqueda = new javax.swing.JTextField();
        Date_hasta = new com.toedter.calendar.JDateChooser();
        Date_desde = new com.toedter.calendar.JDateChooser();
        lbl_desde = new javax.swing.JLabel();
        lbl_hasta = new javax.swing.JLabel();
        btn_todo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1245, 685));
        setSize(new java.awt.Dimension(1225, 635));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                cerrado(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_movimientos.setModel(modeloTabla);
        jScrollPane1.setViewportView(tabla_movimientos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 1060, 350));

        lbl_overTeibul.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        lbl_overTeibul.setForeground(new java.awt.Color(240, 240, 240));
        lbl_overTeibul.setText("Todos los movimientos");
        getContentPane().add(lbl_overTeibul, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 150, 150, -1));

        btnGroup_selector.add(rbtn_descripcion);
        rbtn_descripcion.setSelected(true);
        rbtn_descripcion.setText("Descripcion");
        getContentPane().add(rbtn_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        btnGroup_selector.add(rbtn_tipoMov);
        rbtn_tipoMov.setText("Tipo de Movimiento");
        getContentPane().add(rbtn_tipoMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        btnGroup_selector.add(rbtn_fecha);
        rbtn_fecha.setText("Rango de Fechas");
        rbtn_fecha.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RFechaSelected(evt);
            }
        });
        getContentPane().add(rbtn_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));
        getContentPane().add(txt_busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 250, -1));
        getContentPane().add(Date_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 120, -1));
        getContentPane().add(Date_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 120, -1));

        lbl_desde.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        lbl_desde.setForeground(new java.awt.Color(240, 240, 240));
        lbl_desde.setText("Desde");
        getContentPane().add(lbl_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, -1));

        lbl_hasta.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        lbl_hasta.setForeground(new java.awt.Color(240, 240, 240));
        lbl_hasta.setText("Hasta");
        getContentPane().add(lbl_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, -1, -1));

        btn_todo.setText("Todo");
        btn_todo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_todoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_todo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-620, -200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrado(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerrado
        Principal principal = factory.principal(usuario);
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrado

    private void btn_todoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_todoActionPerformed
        BaseDatos base = factory.basedatos();
        this.cargarModeloTabla(base.obtenerMovimientosTODOS());
        this.lbl_overTeibul.setText("Todos los movimientos");
    }//GEN-LAST:event_btn_todoActionPerformed

    private void RFechaSelected(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RFechaSelected
        if(rbtn_fecha.isSelected()){
            this.Date_desde.setVisible(true);
            this.Date_hasta.setVisible(true);
            this.lbl_desde.setVisible(true);
            this.lbl_hasta.setVisible(true);
        }
        else{
            this.Date_desde.setVisible(false);
            this.Date_hasta.setVisible(false);
            this.lbl_desde.setVisible(false);
            this.lbl_hasta.setVisible(false);
        }
    }//GEN-LAST:event_RFechaSelected

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String busqueda = this.txt_busqueda.getText();
        BaseDatos base = factory.basedatos();
        
        
        if(rbtn_descripcion.isSelected()){
            this.cargarModeloTabla(base.buscarMovimiento_Descipcion(busqueda));
            this.txt_busqueda.setText("");
            this.lbl_overTeibul.setText("Resultados con la descripcion \""+busqueda+"\""); 
            busqueda = "";
        }else{
            if(rbtn_tipoMov.isSelected()){
                this.cargarModeloTabla(base.buscarMovimiento_TipoMov(busqueda));
                this.txt_busqueda.setText("");
                this.lbl_overTeibul.setText("Resultados con el Tipo de Movimiento \""+busqueda+"\""); 
                busqueda = "";
            }else{
                if(rbtn_fecha.isSelected()){
                    DateFormat df = new SimpleDateFormat("MM-dd-yyyy");
                    String desde = df.format(this.Date_desde.getDate());;
                    String hasta = df.format(this.Date_hasta.getDate());;
                    
                    this.cargarModeloTabla(base.obtenerMovimientosRango(desde, hasta));
                    this.txt_busqueda.setText("");
                    this.lbl_overTeibul.setText("Resultados con el Tipo de Movimiento \""+busqueda+"\""); 
                    busqueda = "";
                    
                }
            }
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaAvanzada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaAvanzada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaAvanzada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaAvanzada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusquedaAvanzada(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_desde;
    private com.toedter.calendar.JDateChooser Date_hasta;
    private javax.swing.ButtonGroup btnGroup_selector;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_todo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_desde;
    private javax.swing.JLabel lbl_hasta;
    private javax.swing.JLabel lbl_overTeibul;
    private javax.swing.JRadioButton rbtn_descripcion;
    private javax.swing.JRadioButton rbtn_fecha;
    private javax.swing.JRadioButton rbtn_tipoMov;
    private javax.swing.JTable tabla_movimientos;
    private javax.swing.JTextField txt_busqueda;
    // End of variables declaration//GEN-END:variables
}
