/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entidades.*;
import Procesos.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

/**
 *
 * @author roban
 */
public class NuevoGasto extends javax.swing.JFrame {

    /**
     * Creates new form AñadirFondos
     */
    private static Factory factory;
    
    public NuevoGasto() {
        initComponents();
        factory = new Factory();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulo = new javax.swing.JLabel();
        txt_fondos = new javax.swing.JTextField();
        lbl_monto = new javax.swing.JLabel();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        lbl_categoria = new javax.swing.JLabel();
        cbox_categoria = new javax.swing.JComboBox<>();
        date_fechaMov = new com.toedter.calendar.JDateChooser();
        lbl_fecha = new javax.swing.JLabel();
        lbl_descripcion = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        lbl_nuevaCat = new javax.swing.JLabel();
        txt_nuevaCat = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Igreso de Gastos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                apertura(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_titulo.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(240, 240, 240));
        lbl_titulo.setText("Ingresar gasto");
        lbl_titulo.setToolTipText("");
        getContentPane().add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 120, -1));
        getContentPane().add(txt_fondos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 219, -1));

        lbl_monto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_monto.setForeground(new java.awt.Color(240, 240, 240));
        lbl_monto.setText("Ingrese monto");
        getContentPane().add(lbl_monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        btn_aceptar.setBackground(new java.awt.Color(0, 0, 0));
        btn_aceptar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btn_aceptar.setForeground(new java.awt.Color(255, 255, 255));
        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        btn_cancelar.setBackground(new java.awt.Color(0, 0, 0));
        btn_cancelar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        lbl_categoria.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_categoria.setForeground(new java.awt.Color(240, 240, 240));
        lbl_categoria.setText("Categoría");
        getContentPane().add(lbl_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        cbox_categoria.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cbox_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbox_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 220, -1));
        getContentPane().add(date_fechaMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 220, -1));

        lbl_fecha.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_fecha.setForeground(new java.awt.Color(240, 240, 240));
        lbl_fecha.setText("Fecha");
        getContentPane().add(lbl_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        lbl_descripcion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_descripcion.setForeground(new java.awt.Color(240, 240, 240));
        lbl_descripcion.setText("Descripcion");
        getContentPane().add(lbl_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        getContentPane().add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 220, -1));

        btn_add.setBackground(new java.awt.Color(0, 0, 0));
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("+");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        lbl_nuevaCat.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_nuevaCat.setForeground(new java.awt.Color(240, 240, 240));
        lbl_nuevaCat.setText("Nueva Categoría");
        getContentPane().add(lbl_nuevaCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
        getContentPane().add(txt_nuevaCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 220, -1));

        btn_agregar.setBackground(new java.awt.Color(0, 0, 0));
        btn_agregar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setText("Ok");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 60, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void apertura(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_apertura
        BaseDatos base = factory.basedatos();
        ArrayList<String> tipoGasto = base.tipoGastos();
        cbox_categoria.removeAllItems();
        for(int i=0; i<tipoGasto.size(); i++){
            cbox_categoria.addItem(tipoGasto.get(i));
        }
        this.lbl_nuevaCat.setVisible(false);
        this.txt_nuevaCat.setVisible(false);
        this.btn_agregar.setVisible(false);
    }//GEN-LAST:event_apertura

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        
        DateFormat df = new SimpleDateFormat("MM-dd-yyyy");

        String descripcion = this.txt_descripcion.getText();
        String tipomovimiento = this.cbox_categoria.getItemAt(cbox_categoria.getSelectedIndex());
        String fecha = df.format(this.date_fechaMov.getDate());
        Double monto = Double.parseDouble("-"+this.txt_fondos.getText());
        Movimiento mov = factory.movimiento(descripcion, tipomovimiento, fecha, monto);
        BaseDatos base = factory.basedatos();
        base.ingresoMovimiento(mov);
        
        this.txt_descripcion.setText("");
        this.txt_fondos.setText("");
        
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        BaseDatos base = factory.basedatos();
        base.addCatGastos(this.txt_nuevaCat.getText());

        ArrayList<String> tipoGasto = base.tipoGastos();
        cbox_categoria.removeAllItems();
        for(int i=0; i<tipoGasto.size(); i++){
            cbox_categoria.addItem(tipoGasto.get(i));
        }

        this.lbl_nuevaCat.setVisible(false);
        this.txt_nuevaCat.setVisible(false);
        this.btn_agregar.setVisible(false);
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        this.lbl_nuevaCat.setVisible(true);
        this.txt_nuevaCat.setVisible(true);
        this.btn_agregar.setVisible(true);
    }//GEN-LAST:event_btn_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirFondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirFondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirFondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirFondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirFondos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JComboBox<String> cbox_categoria;
    private com.toedter.calendar.JDateChooser date_fechaMov;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_categoria;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_monto;
    private javax.swing.JLabel lbl_nuevaCat;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_fondos;
    private javax.swing.JTextField txt_nuevaCat;
    // End of variables declaration//GEN-END:variables
}
